In [1]:
import numpy as np

In [2]:
%history

import numpy as np
%history


In [3]:
#broad casting operation when two arry are not of same dimention but operation still happen (with some conditions)

In [58]:
arr=np.arange(24).reshape((2, 3, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [64]:
arr.transpose((2,0,1))

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [66]:
arr.transpose((1,2,0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [47]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
arr.shape = (8,2)

In [21]:
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [25]:
np.zeros((2,),order='F')

array([0., 0.])

In [27]:
np.empty((2,2)) #it get grapig values

array([[1.29904067e-311, 0.00000000e+000],
       [8.34451079e-308, 5.73116149e-322]])

In [33]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])